home:
   path: /
   defaults: { _controller: 'Dk\Controller\Home::home' }

about:
   path: /a_propos
   defaults: {_controller: 'Dk\Controller\About::main' }

aboutBrain:
   path: /a_propos/cerveau
   defaults: {_controller: 'Dk\Controller\About::brain' }

aboutHeart:
   path: /a_propos/coeur
   defaults: {_controller: 'Dk\Controller\About::heart' }

skills:
   path: /competences
   defaults: {_controller: 'Dk\Controller\Skills::main' }

personalProject:
   path: /projets_perso
   defaults: {_controller: 'Dk\Controller\Project::main' }   

contact:
   path: /contact
   defaults: {_controller: 'Dk\Controller\Contact::main' }